name: depup
on:
  schedule:
    - cron: "14 14 * * *" # Runs at 14:14 UTC every day
  repository_dispatch:
    types: [depup]
  workflow_dispatch:

jobs:
  reviewdog:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-depup@v1
        id: depup
        with:
          file: Dockerfile
          version_name: REVIEWDOG_VERSION
          repo: reviewdog/reviewdog

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): Update reviewdog to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): Update reviewdog to ${{ steps.depup.outputs.latest }}"
          body: |
            Update reviewdog to [v${{ steps.depup.outputs.latest }}](https://github.com/reviewdog/reviewdog/releases/tag/v${{ steps.depup.outputs.latest }})
            Compare [v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }}](https://github.com/reviewdog/reviewdog/compare/v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3Adepup).
          branch: chores/depup/update-reviewdog
          base: main
          labels: "bump:minor" 

  typos:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-depup@v1
        id: depup
        with:
          file: Dockerfile
          version_name: TYPOS_VERSION
          repo: crate-ci/typos

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): Update typos to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): Update typos to ${{ steps.depup.outputs.latest }}"
          body: |
            Update typos to [v${{ steps.depup.outputs.latest }}](https://github.com/crate-ci/typos/releases/tag/v${{ steps.depup.outputs.latest }})
            Compare [v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }}](https://github.com/crate-ci/typos/compare/v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3Adepup).
          branch: chores/depup/update-typos
          base: main
          labels: "bump:minor"
